name: "freeCodeCamp-news-get-action"
description: "freeCodeCamp-news-get-action"
author: ""
inputs:
  newsLink:
    description: "A string in a specific format that contains a link to freeCodeCamp News"
    required: true
  markDownFilePath:
    description: "Path  of the generated MarkDown file and relative path relative to the root folder"
    required: false
    default: "./"

runs:
  using: "node12"
  main: "dist/index.js"
